import asyncio
import json
import time
from typing import Dict, Any, Optional, List, AsyncGenerator
from dataclasses import dataclass
from enum import Enum

import httpx
from pydantic import BaseModel, Field
import tiktoken

from src.utils.config import config


class ModelType(Enum):
    """Available model types."""
    QWEN = "qwen"
    GEMINI_FLASH = "gemini_flash"
    MIMO = "mimo"
    DEEPSEEK = "deepseek"
    GEMINI_PRO = "gemini_pro"


class Message(BaseModel):
    """Chat message."""
    role: str = Field(..., description="Message role (system, user, assistant, tool)")
    content: Optional[str] = Field(default=None, description="Message content")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(default=None, description="Tool calls generated by the model")
    tool_call_id: Optional[str] = Field(default=None, description="Tool call ID for tool responses")
    name: Optional[str] = Field(default=None, description="Name of the tool for tool responses")


class ChatRequest(BaseModel):
    """Chat completion request."""
    model: str = Field(..., description="Model ID")
    messages: List[Message] = Field(..., description="Chat messages")
    temperature: float = Field(default=0.7, ge=0.0, le=2.0, description="Temperature")
    max_tokens: Optional[int] = Field(default=None, description="Maximum tokens to generate")
    stream: bool = Field(default=False, description="Whether to stream response")
    tools: Optional[List[Dict[str, Any]]] = Field(default=None, description="Available tools in OpenAI schema")
    tool_choice: Optional[str] = Field(default=None, description="Tool choice mode (e.g., 'auto')")


class UsageDetails(BaseModel):
    """Usage details from OpenRouter."""
    prompt_tokens: int = Field(..., description="Prompt tokens")
    completion_tokens: int = Field(..., description="Completion tokens")
    total_tokens: int = Field(..., description="Total tokens")
    cost: float = Field(..., description="Cost in USD")
    is_byok: bool = Field(default=False, description="Is BYOK (Bring Your Own Key)")
    prompt_tokens_details: Optional[Dict[str, int]] = Field(default=None, description="Prompt token details")
    cost_details: Optional[Dict[str, float]] = Field(default=None, description="Cost details")
    completion_tokens_details: Optional[Dict[str, int]] = Field(default=None, description="Completion token details")


class ChatResponse(BaseModel):
    """Chat completion response."""
    id: str = Field(..., description="Response ID")
    object: str = Field(..., description="Object type")
    created: int = Field(..., description="Creation timestamp")
    model: str = Field(..., description="Model used")
    provider: str = Field(..., description="Model provider")
    system_fingerprint: Optional[str] = Field(default=None, description="System fingerprint")
    choices: List[Dict[str, Any]] = Field(..., description="Response choices")
    usage: Optional[UsageDetails] = Field(default=None, description="Token usage")


@dataclass
class ModelCapabilities:
    """Model capabilities for routing decisions."""
    max_tokens: int
    supports_tools: bool
    supports_vision: bool
    reasoning_strength: float  # 0-1 scale
    coding_strength: float  # 0-1 scale
    speed: float  # 0-1 scale (higher = faster)
    cost_per_token: float  # USD per 1M tokens (average)


class OpenRouterClient:
    """Client for OpenRouter API."""
    
    def __init__(self):
        self.base_url = config.settings.openrouter_base_url
        self.api_key = config.settings.openrouter_api_key
        self.client = httpx.AsyncClient(
            timeout=config.settings.request_timeout,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "https://agenticai.local",  # Optional
                "X-Title": "AgenticAI",  # Optional
            }
        )
        
        # Model ID mapping
        self.model_ids = {
            ModelType.QWEN: config.settings.model_qwen,
            ModelType.GEMINI_FLASH: config.settings.model_gemini_flash,
            ModelType.MIMO: config.settings.model_mimo,
            ModelType.DEEPSEEK: config.settings.model_deepseek,
            ModelType.GEMINI_PRO: config.settings.model_gemini_pro,
        }
        
        # Model capabilities (approximate, based on documentation)
        self.model_capabilities = {
            ModelType.QWEN: ModelCapabilities(
                max_tokens=32768,
                supports_tools=True,
                supports_vision=False,
                reasoning_strength=0.7,
                coding_strength=0.6,
                speed=0.8,
                cost_per_token=0.5,
            ),
            ModelType.GEMINI_FLASH: ModelCapabilities(
                max_tokens=8192,
                supports_tools=True,
                supports_vision=True,
                reasoning_strength=0.5,
                coding_strength=0.4,
                speed=0.9,
                cost_per_token=0.2,
            ),
            ModelType.MIMO: ModelCapabilities(
                max_tokens=32768,
                supports_tools=True,
                supports_vision=True,
                reasoning_strength=0.9,
                coding_strength=0.7,
                speed=0.6,
                cost_per_token=3.0,
            ),
            ModelType.DEEPSEEK: ModelCapabilities(
                max_tokens=128000,
                supports_tools=True,
                supports_vision=False,
                reasoning_strength=0.6,
                coding_strength=0.9,
                speed=0.7,
                cost_per_token=0.21,
            ),
            ModelType.GEMINI_PRO: ModelCapabilities(
                max_tokens=32768,
                supports_tools=True,
                supports_vision=True,
                reasoning_strength=0.8,
                coding_strength=0.7,
                speed=0.5,
                cost_per_token=3.125,
            ),
        }
        
        # Tokenizer for approximate token counting
        try:
            self.tokenizer = tiktoken.get_encoding("cl100k_base")
        except:
            self.tokenizer = None
    
    async def chat_completion(
        self,
        messages: List[Message],
        model_type: ModelType,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        stream: bool = False,
        tools: Optional[List[Dict[str, Any]]] = None,
    ) -> ChatResponse:
        """Send chat completion request to OpenRouter."""
        model_id = self.model_ids[model_type]
        
        # Use defaults if not provided
        if temperature is None:
            temperature = config.settings.temperature
        if max_tokens is None:
            max_tokens = min(
                config.settings.max_tokens_per_request,
                self.model_capabilities[model_type].max_tokens
            )
        
        request = ChatRequest(
            model=model_id,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
            stream=stream,
            tools=tools,
            tool_choice="auto" if tools else None,
        )
        
        try:
            response = await self.client.post(
                f"{self.base_url}/chat/completions",
                json=request.dict(exclude_none=True),
            )
            response.raise_for_status()
            
            data = response.json()
            
            # Track cost
            if "usage" in data:
                usage = data["usage"]
                input_tokens = usage.get("prompt_tokens", 0)
                output_tokens = usage.get("completion_tokens", 0)
                config.track_cost(model_id, input_tokens, output_tokens)
            
            return ChatResponse(**data)
            
        except httpx.HTTPStatusError as e:
            print(f"HTTP error: {e.response.status_code} - {e.response.text}")
            raise
        except Exception as e:
            print(f"Error in chat completion: {e}")
            raise
    
    async def chat_completion_stream(
        self,
        messages: List[Message],
        model_type: ModelType,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        """Stream chat completion response."""
        model_id = self.model_ids[model_type]
        
        if temperature is None:
            temperature = config.settings.temperature
        if max_tokens is None:
            max_tokens = min(
                config.settings.max_tokens_per_request,
                self.model_capabilities[model_type].max_tokens
            )
        
        request = ChatRequest(
            model=model_id,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
            stream=True,
        )
        
        try:
            async with self.client.stream(
                "POST",
                f"{self.base_url}/chat/completions",
                json=request.dict(exclude_none=True),
                timeout=120.0,
            ) as response:
                response.raise_for_status()
                
                collected_content = []
                async for line in response.aiter_lines():
                    if line.startswith("data: "):
                        data = line[6:]
                        if data == "[DONE]":
                            break
                        
                        try:
                            chunk = json.loads(data)
                            if "choices" in chunk and chunk["choices"]:
                                delta = chunk["choices"][0].get("delta", {})
                                if "content" in delta and delta["content"]:
                                    content = delta["content"]
                                    collected_content.append(content)
                                    yield content
                        except json.JSONDecodeError:
                            continue
            
            # Track cost (approximate)
            if self.tokenizer and collected_content:
                full_response = "".join(collected_content)
                output_tokens = len(self.tokenizer.encode(full_response))
                # Estimate input tokens
                input_messages = "\n".join([m.content for m in messages])
                input_tokens = len(self.tokenizer.encode(input_messages))
                config.track_cost(model_id, input_tokens, output_tokens)
                
        except Exception as e:
            print(f"Error in streaming: {e}")
            raise
    
    def estimate_tokens(self, text: str) -> int:
        """Estimate token count for text."""
        if self.tokenizer:
            return len(self.tokenizer.encode(text))
        # Fallback: approximate 4 chars per token
        return len(text) // 4
    
    def get_model_capabilities(self, model_type: ModelType) -> ModelCapabilities:
        """Get capabilities for a model."""
        return self.model_capabilities[model_type]
    
    def get_available_models(self) -> List[Dict[str, Any]]:
        """Get list of available models with capabilities."""
        models = []
        for model_type, model_id in self.model_ids.items():
            caps = self.model_capabilities[model_type]
            models.append({
                "type": model_type.value,
                "id": model_id,
                "capabilities": {
                    "max_tokens": caps.max_tokens,
                    "supports_tools": caps.supports_tools,
                    "supports_vision": caps.supports_vision,
                    "reasoning_strength": caps.reasoning_strength,
                    "coding_strength": caps.coding_strength,
                    "speed": caps.speed,
                    "cost_per_token": caps.cost_per_token,
                }
            })
        return models
    
    async def close(self):
        """Close HTTP client."""
        await self.client.aclose()
    
    async def __aenter__(self):
        return self
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.close()
    
    async def summarize_content(
        self,
        content: str,
        max_tokens: int = 400,
        model_id: str = "openai/gpt-oss-120b",
    ) -> str:
        """Summarize content using gpt-oss-120b (free model)."""
        try:
            messages = [
                Message(role="system", content="You are a helpful assistant that creates concise summaries. Keep the summary under 400 tokens and preserve key information."),
                Message(role="user", content=f"Summarize the following content concisely:\n\n{content}"),
            ]
            
            # Use a custom request since gpt-oss-120b isn't in our model mapping
            request = ChatRequest(
                model=model_id,
                messages=messages,
                temperature=0.2,  # Low temperature for consistent summarization
                max_tokens=max_tokens,
                stream=False,
            )
            
            response = await self.client.post(
                f"{self.base_url}/chat/completions",
                json=request.dict(exclude_none=True),
            )
            response.raise_for_status()
            
            data = response.json()
            
            # Track cost (free model but still track)
            if "usage" in data:
                usage = data["usage"]
                input_tokens = usage.get("prompt_tokens", 0)
                output_tokens = usage.get("completion_tokens", 0)
                config.track_cost(model_id, input_tokens, output_tokens)
            
            # Extract summary from response
            if "choices" in data and data["choices"]:
                choice = data["choices"][0]
                if "message" in choice and "content" in choice["message"]:
                    return choice["message"]["content"].strip()
            
            return ""
            
        except Exception as e:
            print(f"Error in summarization: {e}")
            # Fallback to simple truncation
            return self._fallback_summary(content, max_tokens)
    
    def _fallback_summary(self, content: str, max_tokens: int) -> str:
        """Fallback summary by truncation when API fails."""
        tokens = self.estimate_tokens(content)
        if tokens <= max_tokens:
            return content
        
        # Simple truncation
        target_chars = max_tokens * 4  # Approximate 4 chars per token
        if len(content) > target_chars:
            return content[:target_chars] + "..."
        return content

    async def extract_memory_facts(
        self,
        content: str,
        model_id: str = "openai/gpt-oss-120b",
    ) -> List[str]:
        """Extract factual memories from a chat conversation."""
        try:
            messages = [
                Message(role="system", content="Did the user mention any new facts about themselves, their preferences, or their project details in the following text? If yes, extract them as concise bullet points. If no, return the string 'NO_FACTS'."),
                Message(role="user", content=f"Text to extract facts from:\n\n{content}"),
            ]
            
            request = ChatRequest(
                model=model_id,
                messages=messages,
                temperature=0.1,
                max_tokens=300,
                stream=False,
            )
            
            response = await self.client.post(
                f"{self.base_url}/chat/completions",
                json=request.dict(exclude_none=True),
            )
            response.raise_for_status()
            
            data = response.json()
            
            if "choices" in data and data["choices"]:
                choice = data["choices"][0]
                if "message" in choice and "content" in choice["message"]:
                    content_result = choice["message"]["content"].strip()
                    if content_result == "NO_FACTS" or "NO_FACTS" in content_result:
                        return []
                    
                    # Split bullet points
                    facts = []
                    for line in content_result.split("\n"):
                        line = line.strip()
                        if line.startswith("-") or line.startswith("*"):
                            facts.append(line.lstrip("-* "))
                        elif line and not line.lower().startswith("here"):
                            facts.append(line)
                    return facts
            
            return []
            
        except Exception as e:
            print(f"Error in extracting memory facts: {e}")
            return []

    async def extract_tags(
        self,
        content: str,
        model_id: Optional[str] = None,
        use_heuristic: bool = True,
    ) -> List[str]:
        """Extract tags from content using LLM or heuristic."""
        # If model is specified, use LLM
        if model_id:
            try:
                messages = [
                    Message(role="system", content="Extract 3-5 key topic tags from the content. Return only comma-separated tags, no explanations."),
                    Message(role="user", content=f"Extract tags from:\n\n{content}"),
                ]
                
                request = ChatRequest(
                    model=model_id,
                    messages=messages,
                    temperature=0.1,
                    max_tokens=100,
                    stream=False,
                )
                
                response = await self.client.post(
                    f"{self.base_url}/chat/completions",
                    json=request.dict(exclude_none=True),
                )
                response.raise_for_status()
                
                data = response.json()
                
                # Track cost
                if "usage" in data:
                    usage = data["usage"]
                    input_tokens = usage.get("prompt_tokens", 0)
                    output_tokens = usage.get("completion_tokens", 0)
                    config.track_cost(model_id, input_tokens, output_tokens)
                
                # Parse tags
                if "choices" in data and data["choices"]:
                    choice = data["choices"][0]
                    if "message" in choice and "content" in choice["message"]:
                        tags_text = choice["message"]["content"].strip()
                        tags = [tag.strip() for tag in tags_text.split(",") if tag.strip()]
                        return tags
                
            except Exception as e:
                print(f"Error in tag extraction with LLM: {e}")
                # Fall back to heuristic if LLM fails
                if use_heuristic:
                    return self._heuristic_tags(content)
                return []
        
        # Use heuristic if no model or fallback
        if use_heuristic:
            return self._heuristic_tags(content)
        
        return []
    
    def _heuristic_tags(self, content: str) -> List[str]:
        """Extract tags using simple heuristics."""
        import re
        
        # Common stop words to filter out
        stop_words = {"the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for", "of", "with", "by", "is", "are", "was", "were", "be", "been", "being"}
        
        # Extract words (3+ letters) that appear multiple times
        words = re.findall(r'\b[a-zA-Z]{3,}\b', content.lower())
        word_counts = {}
        
        for word in words:
            if word not in stop_words:
                word_counts[word] = word_counts.get(word, 0) + 1
        
        # Get top 5 most frequent words as tags
        tags = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)[:5]
        return [tag[0] for tag in tags]


# Helper function to create message list
def create_messages(system_prompt: str, user_message: str) -> List[Message]:
    """Create message list from system prompt and user message."""
    return [
        Message(role="system", content=system_prompt),
        Message(role="user", content=user_message),
    ]